# Writes the formal definition and the diagram of every transducer into docs/diagrams.
# The diagrams use Mermaid, so GitHub shows them directly in the markdown files.
#
# Run from the resumelens folder:
#     python -m resumelens.docs_export

import os

from resumelens.normalization.transducers import CATEGORY_TRANSDUCERS, PREPROCESSING_TRANSDUCER

DOCS_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "docs", "diagrams")

EPSILON = "ε"


def show_symbol(symbol):
    if symbol == " ":
        return "␣"
    return symbol


def show_output(output):
    if len(output) == 0:
        return EPSILON
    return " ".join(output)


def join_symbols(symbols):
    shown = []
    for symbol in symbols:
        shown.append("`" + show_symbol(symbol) + "`")
    return ", ".join(shown)


def transducer_to_markdown(transducer):
    lines = []
    lines.append("M = (Q, Σ, Γ, δ, ω, q0, F)")
    lines.append("")
    lines.append("- **Q** (" + str(len(transducer.states)) + " states) = {" + ", ".join(transducer.states) + "}")
    lines.append("- **Σ** = {" + join_symbols(transducer.input_alphabet) + "}")
    lines.append("- **Γ** = {" + join_symbols(transducer.output_alphabet) + "}")
    lines.append("- **q0** = " + transducer.start_state)
    lines.append("- **F** = {" + ", ".join(transducer.final_states) + "}")
    lines.append("- **δ** and **ω** (" + str(len(transducer.transitions)) + " transitions). "
                 "Each row is δ(state, input) = next state and ω(state, input) = output. "
                 "Every pair that is not in the table is undefined, so the input is rejected.")
    lines.append("")
    lines.append("| state | input | δ: next state | ω: output |")
    lines.append("|---|---|---|---|")
    for from_state, symbol, to_state, output in transducer.transitions:
        lines.append("| " + from_state + " | `" + show_symbol(symbol) + "` | " + to_state + " | " + show_output(output) + " |")
    return "\n".join(lines)


def edge_labels(transducer):
    # Joins all the transitions that go between the same two states into one label
    labels = {}
    order = []
    for from_state, symbol, to_state, output in transducer.transitions:
        key = (from_state, to_state)
        if key not in labels:
            labels[key] = []
            order.append(key)
        labels[key].append(show_symbol(symbol) + " / " + show_output(output))
    return order, labels


def preprocessing_labels():
    # The preprocessing transducer has 71 loops on q0, so the diagram groups them
    return [
        "A..Z / a..z",
        "a..z / a..z",
        "0..9 / 0..9",
        "+ / +,  # / #",
        "␣ . - _ / / " + EPSILON,
    ]


def transducer_to_mermaid(transducer):
    lines = ["```mermaid", "flowchart LR"]
    lines.append("    start(( )) --> " + transducer.start_state)
    for state in transducer.final_states:
        lines.append("    " + state + "(((" + state + ")))")

    if transducer is PREPROCESSING_TRANSDUCER:
        for label in preprocessing_labels():
            lines.append("    q0 -- \"" + label + "\" --> q0")
    else:
        order, labels = edge_labels(transducer)
        for from_state, to_state in order:
            label = ", ".join(labels[(from_state, to_state)])
            lines.append("    " + from_state + " -- \"" + label + "\" --> " + to_state)
    lines.append("```")
    return "\n".join(lines)


def write_transducer_doc(transducer, title, folder):
    text = "# " + title + "\n\n"
    text = text + "_Generated by `python -m resumelens.docs_export` from the pyformlang objects._\n\n"
    text = text + "## Diagram\n\n" + transducer_to_mermaid(transducer) + "\n\n"
    text = text + "## Formal definition\n\n" + transducer_to_markdown(transducer) + "\n"

    os.makedirs(folder, exist_ok=True)
    path = os.path.join(folder, transducer.name.lower() + ".md")
    with open(path, "w", encoding="utf-8") as file:
        file.write(text)
    return path


def export_transducers():
    folder = os.path.join(DOCS_DIR, "transducers")
    paths = [write_transducer_doc(PREPROCESSING_TRANSDUCER, "Transducer PREPROCESSING", folder)]
    for category in CATEGORY_TRANSDUCERS:
        paths.append(write_transducer_doc(CATEGORY_TRANSDUCERS[category], "Transducer " + category, folder))
    return paths


if __name__ == "__main__":
    for path in export_transducers():
        print("written", path)
